var Tabletop = require('./vendor/tabletop.js');
var LibHours = require('./libhours.js');

var testURL = 'https://docs.google.com/spreadsheet/pub?hl=en_US&hl=en_US&key=1aEV-CZIqJD9hHJWNWTWIN0I4Cgz3M8jpl4hQwA9l8JU&output=html';

function onLoad(data, tabletop) {
  console.log(data);
};

var options = {
  key: testURL,
  callback: processTerms,
  simpleSheet: false,
  prettyColumnNames: false

};
var nonprettyTermsObject;

// what to do with the hoursObject once it's been built
function processTerms(data, tabletop) {

    nonprettyTermsObject = LibHours.buildNormalHoursObject(data);
	//console.log(nonprettyTermsObject);

    Tabletop.init({
        // key is generated by Google doc
        key: '1aEV-CZIqJD9hHJWNWTWIN0I4Cgz3M8jpl4hQwA9l8JU',

        // function to call when the data is retrieved
        callback: processReasons,
        simpleSheet: false

    });
}

function processReasons(data, tabletop) {

	//console.log(nonprettyTermsObject);
    var prettyTermsObject = LibHours.convertReasons(nonprettyTermsObject, data);
    console.log(JSON.stringify(prettyTermsObject));
}

Tabletop.init(options);