// what to do with the hoursObject once it's been built
function processTerms(data, tabletop) {

    var object = buildNormalHoursObject(data);
    document.write(JSON.stringify(object));
}

window.onload = function() {
    // call this when you are ready to get the data and use it
    Tabletop.init({
        // key is generated by Google doc
        key: '1aEV-CZIqJD9hHJWNWTWIN0I4Cgz3M8jpl4hQwA9l8JU',

        // function to call when the data is retrieved
        //callback: processHours,
        callback: processTerms,

        simpleSheet: false
    });
}