// what to do with the hoursObject once it's been built
function processHours(data, tabletop) {
    // get page_date however you want, I'm just defaulting to new Date

    var date = new Date(2015, 1, 28);
    var moment_date = moment(date);

    var object = buildNormalHoursObject(data, date, "Barker Library");
    document.write(JSON.stringify(object));
}

function processSemester(data, tabletop) {
   
    var completeHoursObject = getSemester(data);
    document.write(JSON.stringify(completeHoursObject));
}

window.onload = function() {
    // call this when you are ready to get the data and use it
    Tabletop.init({
        // key is generated by Google doc
        key: '1aEV-CZIqJD9hHJWNWTWIN0I4Cgz3M8jpl4hQwA9l8JU',

        // function to call when the data is retrieved
        callback: processHours,
        //callback: processSemester,

        simpleSheet: false
    });
}